package com.bkrmalick.covidtracker.models.dynamo_db;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.bkrmalick.covidtracker.util.DateTimeUtils;

import java.util.Map;
import java.util.UUID;

@DynamoDBTable(tableName = "covidtracker.form-response")
public class FormResponseRecord
{
	private String id;
	private Map<String, String> answersMap;
	private String createdDate;

	public FormResponseRecord()
	{
	}

	public FormResponseRecord(Map<String,String> answersMap)
	{
		this.id = UUID.randomUUID().toString();
		this.answersMap = answersMap;
		this.createdDate = DateTimeUtils.getDateTimeNowInUTC().toString();
	}

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public String getId()
	{
		return id;
	}

	public void setId(String id)
	{
		this.id = id;
	}

	@DynamoDBAttribute
	public Map<String, String> getAnswersMap()
	{
		return answersMap;
	}

	public void setAnswersMap(Map<String, String> answersMap)
	{
		this.answersMap = answersMap;
	}

	@DynamoDBAttribute
	public String getCreatedDate()
	{
		return createdDate;
	}

	public void setCreatedDate(String createdDate)
	{
		this.createdDate = createdDate;
	}

	@Override
	public String toString()
	{
		return "FormResponseRecord{" +
				"id='" + id + '\'' +
				", answersMap=" + answersMap +
				", createdDate='" + createdDate + '\'' +
				'}';
	}
}